name: GitHub CI

permissions:
  contents: write

on:
-   push
-   pull_request
-   workflow_dispatch

jobs:
    windowsBuild:
        name: Windows Build
        runs-on: windows-latest
        env:
            LLVM_VERSION: 22.1.6
            LLVM_MAJOR_VERSION: 22

        strategy:
            fail-fast: false
            matrix:
                CRT:
                -   msvcrt
                -   libcmt

                TARGET_CPU:
                -   amd64

                CONFIGURATION:
                -   Debug
                -   Release

        steps:
        -   name: Checkout repo
            uses: actions/checkout@v2

        -   name: Install
            shell: cmd
            run: |
                call %GITHUB_WORKSPACE%\set-env.bat msvc17 ${{matrix.CRT}} ${{matrix.TARGET_CPU}} ${{matrix.CONFIGURATION}}
                call %GITHUB_WORKSPACE%\install.bat

        -   name: Build and test
            id: BUILD
            shell: cmd
            run: |
                call %GITHUB_WORKSPACE%\set-env.bat msvc17 ${{matrix.CRT}} ${{matrix.TARGET_CPU}} ${{matrix.CONFIGURATION}}
                call %GITHUB_WORKSPACE%\build.bat
                echo DEPLOY_FILE=%DEPLOY_FILE% >> %GITHUB_OUTPUT%

        -   name: Release
            uses: softprops/action-gh-release@v3
            with:
                tag_name: v${{ env.LLVM_VERSION }}-${{github.run_number}}
                files: ${{steps.BUILD.outputs.DEPLOY_FILE}}
                token: ${{secrets.GITHUB_TOKEN}}
